### ISSUE TITLE
KeyVault Connectivity Error - NullReferenceException in GetAllValues

### ISSUE THREAD

**Issue by kamalsivalingam** [aspnet/MicrosoftConfigurationBuilders#140]
We are noticing KeyVault connectivity errors with NullReferenceException while deploying many applications (.Net Framework and .Net Core Apps) at the same time. For .Net Framework Apps how many calls are made to AppConfig and KeyVault for an App? Are these calls per configuration?During AppPool recycle and windows service restart, we see close to 5000 to 6000 calls, though we have less than 15 services.

Exception Info: System.NullReferenceException
   at Microsoft.Configuration.ConfigurationBuilders.AzureKeyVaultConfigBuilder.GetAllValues(System.String)
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.EnsureGreedyInitialized()

Exception Info: System.Exception
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.EnsureGreedyInitialized()
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.ProcessConfigurationSection(System.Configuration.ConfigurationSection)
   at System.Configuration.ConfigurationBuilderChain.ProcessConfigurationSection(System.Configuration.ConfigurationSection)
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigurationBuilderHost.ProcessConfigurationSection(System.Configuration.ConfigurationSection, System.Configuration.ConfigurationBuilder)
   at System.Configuration.Internal.DelegatingConfigHost.ProcessConfigurationSection(System.Configuration.ConfigurationSection, System.Configuration.ConfigurationBuilder)
   at System.Configuration.BaseConfigurationRecord.CallHostProcessConfigurationSection(System.Configuration.ConfigurationSection, System.Configuration.ConfigurationBuilder)
   at System.Configuration.RuntimeConfigurationRecord+RuntimeConfigurationFactory.CreateSectionImpl(System.Configuration.RuntimeConfigurationRecord, System.Configuration.FactoryRecord, System.Configuration.SectionRecord, System.Configuration.SectionInput, System.Object, System.Configuration.ConfigXmlReader)
   at System.Configuration.RuntimeConfigurationRecord+RuntimeConfigurationFactory.CreateSectionWithRestrictedPermissions(System.Configuration.RuntimeConfigurationRecord, System.Configuration.FactoryRecord, System.Configuration.SectionRecord, System.Configuration.SectionInput, System.Object, System.Configuration.ConfigXmlReader)
   at System.Configuration.RuntimeConfigurationRecord.CreateSection(Boolean, System.Configuration.FactoryRecord, System.Configuration.SectionRecord, System.Configuration.SectionInput, System.Object, System.Configuration.ConfigXmlReader)
   at System.Configuration.BaseConfigurationRecord.CallCreateSection(Boolean, System.Configuration.FactoryRecord, System.Configuration.SectionRecord, System.Configuration.SectionInput, System.Object, System.Configuration.ConfigXmlReader)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(System.String[], System.Configuration.SectionInput, Boolean, System.Configuration.FactoryRecord, System.Configuration.SectionRecord, System.Object)
   at System.Configuration.BaseConfigurationRecord.Evaluate(System.Configuration.FactoryRecord, System.Configuration.SectionRecord, System.Object, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.ConfigurationManager.get_AppSettings()

**Comment by StephenMolloy** [comment]
I believe this is fixed by #134 and #163.
